version: '3.3'
services:
  database:
    container_name: database-postgres
    image: postgres:12.16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coffee_shop
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api-server:
    container_name: api-server
    build:
      context: ./
      dockerfile: ./apiServices.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
